version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: m2dd/php
    container_name: ${APP_NAME}
    restart: on-failure
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      - ./src/:/var/www
      - ./m2dd/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: "${APP_NAME}_webserver"
    restart: on-failure
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src/:/var/www
      - ./m2dd/conf.d/:/etc/nginx/conf.d/
      - ./m2dd/ssl/:/etc/ssl/
    networks:
      - app-network

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: "${APP_NAME}_db"
    restart: on-failure
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: magento2
      MYSQL_USER: magento2
      MYSQL_PASSWORD: magento2
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./m2dd/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  #PHPMyAdmin Container
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: "${APP_NAME}_phpmyadmin"
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./m2dd/local.ini:/usr/local/etc/php/conf.d/php-phpmyadmin.ini
    networks:
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
